src/Entity/Reservation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReservationRepository")
 */
class Reservation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Room")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Room;

    /**
     * @ORM\Column(type="date")
     * @Assert\GreaterThanOrEqual(
     * "today",
     * message = "WARNING: Start date should be today or after today."
     * )
     */
    private $DateStart;

    /**
     * @ORM\Column(type="date", nullable=false)
     */
    private $DateEnd;

    private $Length;
    private $Price;

    /**
    * @Assert\EqualTo(
    * false,
    * message = "WARNING: Temporal anomaly detected! Start date should not be after the end date or equal to the end date."
    * )
    */
    private $temporalAnomaly = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getRoom(): ?Room
    {
        return $this->Room;
    }

    public function setRoom(?Room $Room): self
    {
        $this->Room = $Room;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->DateStart;
    }

    public function setDateStart(\DateTimeInterface $DateStart): self
    {
        $this->DateStart = $DateStart;
        
        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->DateEnd;
    }

    public function setDateEnd(?\DateTimeInterface $DateEnd): self
    {
        $this->DateEnd = $DateEnd;
        if ($this->DateStart->diff( $this->DateEnd, FALSE)->invert != 0) {
            $this->temporalAnomaly = true;
        }

        return $this;
    }

    public function getLength(): ?string
    {
        //$this->length = date_diff($this->DateEnd, $this->DateStart, false);
        $this->length =  $this->DateStart->diff( $this->DateEnd, FALSE);
        return $this->length->format('%d');
    }

    public function getPrice(): ?string
    {
        $this->price = $this->length->format('%d') * 20;
        return $this->price;
    }

}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('DateStart')
            ->add('DateEnd')
            ->add('User')
            ->add('Room')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\Reservation1Type;
use App\Repository\ReservationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Dompdf\Dompdf;
use Dompdf\Options;

/**
 * @Route("/reservation")
 */
class ReservationController extends AbstractController
{
    /**
     * @Route("/", name="reservation_index", methods={"GET"})
     */
    public function index(ReservationRepository $reservationRepository): Response
    {
        if ($this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) {
            return $this->render('reservation/index.html.twig', [
                'reservations' => $reservationRepository->findAll(),
            ]);
        }
        else {
            $User = $this->get('security.token_storage')
                ->getToken()
                ->getUser();

            $this->get('doctrine')
                ->getManager()
                ->getRepository('App:Reservation')
                ->findByUser($User);
            
            return $this->render('reservation/index.html.twig', [
                'reservations' => $reservationRepository->findByUser($User),
            ]);
        }
    }

    /**
     * @Route("/new", name="reservation_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(Reservation1Type::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('reservation_index');
        }

        return $this->render('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_show", methods={"GET"})
     */
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reservation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reservation $reservation): Response
    {
        $form = $this->createForm(Reservation1Type::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reservation_index', [
                'id' => $reservation->getId(),
            ]);
        }

        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Reservation $reservation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reservation_index');
    }

    /**
     * @Route("/search", name="reservation_search", methods={"GET","POST"})
     */
    public function search(Request $request): Response
    {
        
    }

    /**
     * @Route("/factuur/{id}", name="reservation_factuur", methods={"GET"})
     */
    public function factuur(Reservation $reservation): Response
    {
        // Configure Dompdf according to your needs
        $pdfOptions = new Options();
        $pdfOptions->set('Arial');
        
        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);
        
        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('reservation/factuur.html.twig', [
            'reservation' => $reservation
        ]);
        
        // Load HTML to Dompdf
        $dompdf->loadHtml($html);
        
        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (inline view)
        $dompdf->stream("mypdf.pdf", [
            "Attachment" => false
        ]);
    }

    /**
     *  @Route("stoday", name="reservation_today", methods={"GET"})
     */
    public function today(ReservationRepository $reservationRepository): Response
    {
        $current_date = new \DateTime();
        $current_date = $current_date->format('Y-m-d');
        if ($this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) {
            return $this->render('reservation/today.html.twig', [
                'reservations' => $reservationRepository->findAllToday($current_date),
            ]);
        }
        else {
            $User = $this->get('security.token_storage')
                ->getToken()
                ->getUser();

            $this->get('doctrine')
                ->getManager()
                ->getRepository('App:Reservation')
                ->findByUser($User);
            
            return $this->render('reservation/today.html.twig', [
                'reservations' => $reservationRepository->findByUserToday($current_date, $User),
            ]);
        }
    }
}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
<div class="container">
    <h1>Edit Reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('reservation_index') }}">back to list</a>

    {{ include('reservation/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/reservation/factuur.html.twig
{% block body %}
    <h1>Factuur</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Reservation Id</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ reservation.id }}</td>
            </tr>
        </tbody>
        <thead>
            <tr>
                <th>User</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ reservation.user }}</td>
            </tr>
        </tbody>
        <thead>
            <tr>
                <th>Start date</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ reservation.DateStart ? reservation.DateStart|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
        <thead>
            <tr>
                <th>End date</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ reservation.DateEnd ? reservation.DateEnd|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
        <thead>
            <tr>
                <th>Length</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ reservation.length }} days</td>
            </tr>
        </tbody>
        <thead>
            <tr>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>&euro; {{ reservation.price }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation index{% endblock %}

{% block body %}
<div class="container">
    {% if is_granted("ROLE_ADMIN") %}
        <h1>Reservation index</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>DateStart</th>
                    <th>DateEnd</th>
                    <th>User</th>
                    <th>Room</th>
                    <th>Length</th>
                    <th>Price</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for reservation in reservations %}
                <tr>
                    <td>{{ reservation.id }}</td>
                    <td>{{ reservation.DateStart ? reservation.DateStart|date('Y-m-d') : '' }}</td>
                    <td>{{ reservation.DateEnd ? reservation.DateEnd|date('Y-m-d') : '' }}</td>
                    <td>{{ reservation.user }}</td>
                    <td>{{ reservation.room }}</td>
                    <td>{{ reservation.length }} days</td>
                    <td>&euro; {{ reservation.price }}</td>
                    <td>
                        <a href="{{ path('reservation_show', {'id': reservation.id}) }}"><button class="actionbutton button-show"></button></a>
                        <a href="{{ path('reservation_edit', {'id': reservation.id}) }}"><button class="actionbutton button-edit"></button></a>
                        <a href="{{ path('reservation_factuur', {'id': reservation.id}) }}"><button class="actionbutton button-factuur"></button></a>
                        <a href="{{ path('reservation_delete', {'id': reservation.id}) }}"><button class="actionbutton button-delete"></button></a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('reservation_new') }}">Create new</a><br />
        <a href="{{ path('reservation_today') }}">Today's checkins and checkouts</a>
    {% elseif is_granted("ROLE_USER") %}
        <h1>Your reservations</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>DateStart</th>
                    <th>DateEnd</th>
                    <th>User</th>
                    <th>Room</th>
                    <th>Length</th>
                    <th>Price</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for reservation in reservations %}
                <tr>
                    <td>{{ reservation.id }}</td>
                    <td>{{ reservation.DateStart ? reservation.DateStart|date('Y-m-d') : '' }}</td>
                    <td>{{ reservation.DateEnd ? reservation.DateEnd|date('Y-m-d') : '' }}</td>
                    <td>{{ reservation.user }}</td>
                    <td>{{ reservation.room }}</td>
                    <td>{{ reservation.length }} days</td>
                    <td>&euro; {{ reservation.price }}</td>
                    <td>
                        <a href="{{ path('reservation_show', {'id': reservation.id}) }}"><button class="actionbutton button-show"></button></a>
                        <a href="{{ path('reservation_edit', {'id': reservation.id}) }}"><button class="actionbutton button-edit"></button></a>
                        <a href="{{ path('reservation_factuur', {'id': reservation.id}) }}"><button class="actionbutton button-factuur"></button></a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('reservation_new') }}">Create new</a><br />
        <a href="{{ path('reservation_today') }}">Today's checkins and checkouts</a>
    {% else %}
        <p>Please log in</p>
    {% endif %}
</div>
{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
<div class="container">
    <h1>Create new Reservation</h1>

    {{ include('reservation/_form.html.twig') }}

    <a href="{{ path('reservation_index') }}">back to list</a>
</div>
{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
<div class="container">
    <h1>Reservation</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>DateStart</th>
                <th>DateEnd</th>
                <th>User</th>
                <th>Room</th>
                <th>Length</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.DateStart ? reservation.DateStart|date('Y-m-d') : '' }}</td>
                <td>{{ reservation.DateEnd ? reservation.DateEnd|date('Y-m-d') : '' }}</td>
                <td>{{ reservation.user }}</td>
                <td>{{ reservation.room }}</td>
                <td>{{ reservation.length }} days</td>
                <td>&euro; {{ reservation.price }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('reservation_index') }}">back to list</a>

    <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('reservation/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/reservation/today.html.twig
{% extends 'base.html.twig' %}

{% block title %}Today's checkins and checkouts{% endblock %}

{% block body %}
<div class="container">
    {% if is_granted("ROLE_ADMIN") %}
        <h1>Today's checkins and checkouts</h1>
        <p>Today is: <b>{{ date() ? date()|date('Y-m-d') : '' }}</b></p>
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>DateStart</th>
                    <th>DateEnd</th>
                    <th>User</th>
                    <th>Room</th>
                    <th>actions</th>
                </tr>
            </thead>
            <tbody>
            {% for reservation in reservations %}
                <tr>
                    <td>{{ reservation.id }}</td>
                    {% if (reservation.DateStart ? reservation.DateStart|date('Y-m-d') : '') == (date() ? date()|date('Y-m-d') : '') %}
                        <td><b>{{ reservation.DateStart ? reservation.DateStart|date('Y-m-d') : '' }}</b></td>
                    {% else %}
                        <td>{{ reservation.DateStart ? reservation.DateStart|date('Y-m-d') : '' }}</td>
                    {% endif %}
                    {% if (reservation.DateEnd ? reservation.DateEnd|date('Y-m-d') : '') == (date() ? date()|date('Y-m-d') : '') %}
                        <td><b>{{ reservation.DateEnd ? reservation.DateEnd|date('Y-m-d') : '' }}</b></td>
                    {% else %}
                        <td>{{ reservation.DateEnd ? reservation.DateEnd|date('Y-m-d') : '' }}</td>
                    {% endif %}
                    <td>{{ reservation.user }}</td>
                    <td>{{ reservation.room }}</td>
                    <td>{{ reservation.length }} days</td>
                    <td>&euro; {{ reservation.price }}</td>
                    <td>
                        <a href="{{ path('reservation_show', {'id': reservation.id}) }}"><button class="actionbutton button-show"></button></a>
                        <a href="{{ path('reservation_edit', {'id': reservation.id}) }}"><button class="actionbutton button-edit"></button></a>
                        <a href="{{ path('reservation_factuur', {'id': reservation.id}) }}"><button class="actionbutton button-factuur"></button></a>
                        <a href="{{ path('reservation_delete', {'id': reservation.id}) }}"><button class="actionbutton button-delete"></button></a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% elseif is_granted("ROLE_USER") %}
        <h1>Your checkins and checkouts of today</h1>
        <p>Today is: <b>{{ date() ? date()|date('Y-m-d') : '' }}</b></p>
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>DateStart</th>
                    <th>DateEnd</th>
                    <th>User</th>
                    <th>Room</th>
                    <th>Length</th>
                    <th>Price</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for reservation in reservations %}
                <tr>
                    <td>{{ reservation.id }}</td>
                    {% if  (reservation.DateStart ? reservation.DateStart|date('Y-m-d') : '') == (date() ? date()|date('Y-m-d') : '') %}
                        <td><b>{{ reservation.DateStart ? reservation.DateStart|date('Y-m-d') : '' }}</b></td>
                    {% else %}
                        <td>{{ reservation.DateStart ? reservation.DateStart|date('Y-m-d') : '' }}</td>
                    {% endif %}
                    {% if (reservation.DateEnd ? reservation.DateEnd|date('Y-m-d') : '') == (date() ? date()|date('Y-m-d') : '') %}
                        <td><b>{{ reservation.DateEnd ? reservation.DateEnd|date('Y-m-d') : '' }}</b></td>
                    {% else %}
                        <td>{{ reservation.DateEnd ? reservation.DateEnd|date('Y-m-d') : '' }}</td>
                    {% endif %}
                    <td>{{ reservation.user }}</td>
                    <td>{{ reservation.room }}</td>
                    <td>{{ reservation.length }} days</td>
                    <td>&euro; {{ reservation.price }}</td>
                    <td>
                        <a href="{{ path('reservation_show', {'id': reservation.id}) }}"><button class="actionbutton button-show"></button></a>
                        <a href="{{ path('reservation_factuur', {'id': reservation.id}) }}"><button class="actionbutton button-factuur"></button></a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Please log in</p>
    {% endif %}
</div>
{% endblock %}